/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenIndexRouteImport } from './routes/token/index'
import { Route as TokenRequestRouteImport } from './routes/token/request'
import { Route as TokenHistoryRouteImport } from './routes/token/history'
import { Route as dashboardingTestMockRouteImport } from './routes/(dashboarding)/test-mock'
import { Route as dashboardingTasksRouteImport } from './routes/(dashboarding)/tasks'
import { Route as dashboardingHelloRouteImport } from './routes/(dashboarding)/hello'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenIndexRoute = TokenIndexRouteImport.update({
  id: '/token/',
  path: '/token/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRequestRoute = TokenRequestRouteImport.update({
  id: '/token/request',
  path: '/token/request',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenHistoryRoute = TokenHistoryRouteImport.update({
  id: '/token/history',
  path: '/token/history',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardingTestMockRoute = dashboardingTestMockRouteImport.update({
  id: '/(dashboarding)/test-mock',
  path: '/test-mock',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardingTasksRoute = dashboardingTasksRouteImport.update({
  id: '/(dashboarding)/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardingHelloRoute = dashboardingHelloRouteImport.update({
  id: '/(dashboarding)/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/generate': typeof GenerateRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/hello': typeof dashboardingHelloRoute
  '/tasks': typeof dashboardingTasksRoute
  '/test-mock': typeof dashboardingTestMockRoute
  '/token/history': typeof TokenHistoryRoute
  '/token/request': typeof TokenRequestRoute
  '/token': typeof TokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/generate': typeof GenerateRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/hello': typeof dashboardingHelloRoute
  '/tasks': typeof dashboardingTasksRoute
  '/test-mock': typeof dashboardingTestMockRoute
  '/token/history': typeof TokenHistoryRoute
  '/token/request': typeof TokenRequestRoute
  '/token': typeof TokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/generate': typeof GenerateRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(dashboarding)/hello': typeof dashboardingHelloRoute
  '/(dashboarding)/tasks': typeof dashboardingTasksRoute
  '/(dashboarding)/test-mock': typeof dashboardingTestMockRoute
  '/token/history': typeof TokenHistoryRoute
  '/token/request': typeof TokenRequestRoute
  '/token/': typeof TokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/generate'
    | '/login'
    | '/signup'
    | '/hello'
    | '/tasks'
    | '/test-mock'
    | '/token/history'
    | '/token/request'
    | '/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/generate'
    | '/login'
    | '/signup'
    | '/hello'
    | '/tasks'
    | '/test-mock'
    | '/token/history'
    | '/token/request'
    | '/token'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/generate'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(dashboarding)/hello'
    | '/(dashboarding)/tasks'
    | '/(dashboarding)/test-mock'
    | '/token/history'
    | '/token/request'
    | '/token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  GenerateRoute: typeof GenerateRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  dashboardingHelloRoute: typeof dashboardingHelloRoute
  dashboardingTasksRoute: typeof dashboardingTasksRoute
  dashboardingTestMockRoute: typeof dashboardingTestMockRoute
  TokenHistoryRoute: typeof TokenHistoryRoute
  TokenRequestRoute: typeof TokenRequestRoute
  TokenIndexRoute: typeof TokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/': {
      id: '/token/'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/request': {
      id: '/token/request'
      path: '/token/request'
      fullPath: '/token/request'
      preLoaderRoute: typeof TokenRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/history': {
      id: '/token/history'
      path: '/token/history'
      fullPath: '/token/history'
      preLoaderRoute: typeof TokenHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboarding)/test-mock': {
      id: '/(dashboarding)/test-mock'
      path: '/test-mock'
      fullPath: '/test-mock'
      preLoaderRoute: typeof dashboardingTestMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboarding)/tasks': {
      id: '/(dashboarding)/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof dashboardingTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboarding)/hello': {
      id: '/(dashboarding)/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof dashboardingHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  GenerateRoute: GenerateRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  dashboardingHelloRoute: dashboardingHelloRoute,
  dashboardingTasksRoute: dashboardingTasksRoute,
  dashboardingTestMockRoute: dashboardingTestMockRoute,
  TokenHistoryRoute: TokenHistoryRoute,
  TokenRequestRoute: TokenRequestRoute,
  TokenIndexRoute: TokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
